#!/bin/sh

dizo="B4:9A:95:7D:0C:01"
connect=$(bluetoothctl info $dizo | grep Connected | awk '{print $2}')
if [ $connect = no ]
then
        notify-send "Connecting to Dizo"
        bluetoothctl connect $dizo || notify-send "Failed to Connect"
else
        notify-send "Disconnecting from Dizo"
        bluetoothctl disconnect $dizo
fi

exec ~/.config/scripts/audioswitch
