#!/bin/sh                                         

########## BSPWM ##########
sudo pacman -Syu 
sudo pacman -S --noconfirm bspwm sxhkd rofi slock dunst lxappearance maim alsa-utils dbus-python

cp -r ~/dotfiles/{.zshrc,.local,.fonts,.xinitrc,.imwheelrc,.xprofile,.zprofile,.tmux.conf,.icons,.themes} ~/
cp -r ~/dotfiles/.local/bin/* ~/.local/bin && cp -r ~/dotfiles/.local/share/* ~/.local/share
cp -r ~/dotfiles/.config/. ~/.config
chmod +x ~/.config/bspwm/bspwmrc ~/.config/polybar/launch.sh ~/.local/bin/scripts/* ~/.config/sxiv/exec/key-handler

mkdir ~/{desk,dox,dl,music,templates,pub,pix,vids,code,imp} 

git clone https://github.com/LukeSmithxyz/st.git ~/dl/st
cd ~/dl/st && sudo make clean install

git clone https://github.com/LukeSmithxyz/dmenu.git ~/dl/dmenu
cd ~/dl/dmenu && sudo make clean install

git clone https://github.com/dracula/gtk.git ~/.themes/Dracula
sudo cp -r ~/.icons/PapirusFlatMix/cursors /usr/share/icons/Adwaita 
sudo cp -r ~/.icons/PapirusFlatMix /usr/share/icons
sudo cp -r ~/.themes/* /usr/share/themes

sudo pacman -S --noconfirm ttf-jetbrains-mono ttf-joypixels ttf-font-awesome \
     noto-fonts noto-fonts-emoji noto-fonts-cjk terminus-font \
     cargo linux-headers firefox \
     wget curl fzf aria2 tmux kitty \
     neovim ripgrep qt5ct kvantum qt6ct \
     mate-calc reflector \
     dialog cmake libconfig dash wmctrl imwheel \
     pipewire pulseaudio pavucontrol playerctl wmname \
     wireless_tools net-tools nm-connection-editor \
     tree ncdu thunar thunar-archive-plugin ranger rsync unrar unzip zip p7zip tar \
     htop neofetch bpytop zathura zathura-pdf-mupdf \
     speedtest-cli trash-cli yt-dlp transmission-cli \
     imagemagick sxiv xwallpaper ffmpeg python-pywal mpv \
     intel-ucode virtualbox-guest-utils python-pip xdotool \
     zsh-syntax-highlighting zsh-completions zsh-autosuggestions \
     unclutter jq xdg-user-dirs xorg xclip openssh-runit
     
#xorg-server xorg-xinit xorg-xkill xorg-xsetroot xorg-xbacklight xorg-xprop
#brightnessctl dash cowsay libnotify connman libconfig pipewire pipewire-pulse

#linux-lts linux-lts-headers
cargo install ttyper lsd exa bat

sudo pacman -S lightdm-runit lightdm-gtk-greeter lightdm-gtk-greeter-settings
#dm-tool switch-to-greeter
#sudo ln -s /etc/runit/sv/lightdm /run/runit/service  ( artix )
#sudo systemctl enable lightdm.service  ( arch )

sudo pacman -S --noconfirm nvidia nvidia-utils nvidia-settings opencl-nvidia \
scrcpy android-tools nvtop stress \
obs-studio audacity gimp inkscape virtualbox kdeconnect blender discord docker \
telegram-desktop xfce4 xfce4-goodies \
blueman bluez bluez-utils ntfs-3g \
virt-manager qemu bridge-utils dnsmasq openbsd-netcat ovmf qemu-arch-extra

#sudo pacman -Rns xfce4-screensaver xfce4-clipman-plugin xfce4-weather-plugin xfce4-notes-plugin

##### Setup Virtmanager in Arch #####
#sudo systemctl enable --now libvirtd
#sudo vim /etc/libvirt/libvirtd.conf  #uncmnt line 81,104
#sudo usermod -aG libvirt bot
#sudo systemctl restart libvirtd
#sudo virsh net-define /etc/libvirt/qemu/networks/default.xml
#sudo virsh net-autostart default

#sudo systemctl enable bluetooth  ( arch )
#sudo systemctl enable bluetooth.service  ( arch )
#sudo systemctl enable fstrim.timer  ( arch )

git clone https://aur.archlinux.org/paru.git ~/paru
cd ~/paru && makepkg -si
paru -S --noconfirm spotify-adblock notion-app google-chrome cava ly polybar preload visual-studio-code-bin plymouth-nosystemd libxft-bgra  

#sudo systemctl enable ly.service  ( arch )

sudo cat <<EOF | sudo tee /etc/resolv.conf 
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF
 
#xdg-mime query filetype (file)  #check filetype
#xdg-mime query default (file/type)  #check default app of filetype
xdg-mime default sxiv.desktop image/jpeg
xdg-mime default sxiv.desktop image/jpg
xdg-mime default sxiv.desktop image/png
xdg-mime default inkscape.desktop image/svg+xml
xdg-mime default org.pwmt.zathura.desktop application/pdf

#Boost Linux
#sudo systemctl enable vboxservice  ( arch )
GRUB_CMDLINE_LINUX="rhgb quiet mitigations=off"

sudo setfont /usr/share/kbd/consolefonts/ter-c16b.psf.gz
sudo su root -c "echo -e FONT='Uni2-TerminusBold20x10.psf.gz' >> /etc/default/console-setup"

# uncmnt zsh plugins path for arch
# vim /etc/pacman.conf  # uncheck ignorepkg and put pkgname
# export LC_CTYPE="en_GB.utf8"  ( fix suckless utilities give XOpenIM failed error )
#QT_QPA_PLATFORMTHEME="qt5ct" > /etc/environment  ( fix qt5ct )
#ControllerMode = bredr > /etc/bluetooth/main.conf  ( fix bluetooth )

