#!/bin/sh


#pulsemixer playerctl

sudo pacman -Sy bspwm sxhkd dmenu rofi kitty dunst nitrogen lxappearance scrot xfce4-terminal alsa-utils 


git clone https://github.com/sayanta01/dotfiles ~/Desktop/dotfiles
cp -r ~/Desktop/dotfiles/{.zshrc,.vimrc,.fonts,.xinitrc} ~/
cp -r ~/Desktop/dotfiles/.config/* ~/.config
chmod +x ~/.config/bspwm/bspwmrc ~/.config/polybar/launch.sh ~/.config/polybar/scripts/* 


cd ~/Desktop/dotfiles/.config/st
sudo make clean install && bash STcolor

cd ~/.config/dmenu
sudo make clean install

