#!/bin/sh                                         

sudo pacman -Syyu 
cp -r ~/dotfiles/{.zshrc,.zprofile,.profile,.xprofile,.imwheelrc} ~/
cp -r ~/dotfiles/.local/bin/* ~/.local/bin && cp -r ~/dotfiles/.local/share/* ~/.local/share && cp -r ~/dotfiles/.config/. ~/.config
chmod -R +x ~/.config/bspwm/ ~/.config/polybar/launch.sh ~/.config/sxhkd/sxhkd.sh ~/.local/bin/ ~/.config/sxiv/ ~/.config/lf/{scope,cleaner}

mkdir ~/{desk,dox,dl,music,vids,pix,templates,pub,code,imp} 

git clone https://github.com/LukeSmithxyz/st.git ~/dl/st
cd ~/dl/st && sudo make clean install

git clone https://github.com/LukeSmithxyz/dmenu.git ~/dl/dmenu
cd ~/dl/dmenu && sudo make clean install

git clone https://github.com/sayanta01/nvim ~/.config/nvim

git clone https://github.com/sayanta01/PapirusFlatMix ~/.local/share/icons/PapirusFlatMix
sudo cp -r ~/.local/share/icons/PapirusFlatMix/cursors /usr/share/icons/Adwaita 
sudo cp -r ~/.local/share/icons/PapirusFlatMix /usr/share/icons
sudo cp -r ~/.local/share/themes/* /usr/share/themes

sudo pacman -S --noconfirm ttf-jetbrains-mono ttf-joypixels ttf-font-awesome \
     noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-roboto terminus-font \
     exa bat tldr fd ripgrep procs duf dust \
     mate-calc rsync wget curl man fzf aria2 \
     cargo linux-headers firefox meld neovim kitty \
     neofetch htop bpytop cowsay libconfig gnome-keyring \
     bspwm polybar sxhkd rofi dunst libnotify \
     qt5ct qt6ct kvantum lxappearance xcape \
     pavucontrol playerctl mpd ncmpcpp dbus-python \
     dialog cmake jq wmname imwheel \
     wireless_tools net-tools nm-connection-editor network-manager-applet dnsutils \
     mpv mediainfo perl-image-exiftool ffmpegthumbnailer imagemagick maim sxiv xwallpaper ffmpeg python-pip python-pywal \
     unrar unzip zip p7zip tar engrampa lf \
     tree ncdu thunar thunar-archive-plugin thunar-media-tags-plugin \
     zathura zathura-pdf-mupdf ghostscript \
     zsh-syntax-highlighting zsh-completions zsh-autosuggestions \
     trash-cli yt-dlp transmission-cli \
     intel-ucode virtualbox-guest-utils \
     xdg-utils xdg-user-dirs xdo xclip xdotool wmctrl
# socat exfat-utils brightnessctl  - additional tools 

# use PipeWire
# sudo pacman -S pipewire pipewire-pulse wireplumber 
# use PulseAudio
# sudo pacman -S pulseaudio pulseaudio-bluetooth 

sudo pacman -S --noconfirm lightdm-gtk-greeter lightdm-gtk-greeter-settings grub-customizer
# lightdm-runit  ( artix )
#lightdm  ( arch )
# dm-tool switch-to-greeter 
# /etc/lightdm/lightdm-gtk-greeter.conf >> background = /etc/lightdm/bg.png  ( move any bg to /etc/lightdm )
# sudo ln -s /etc/runit/sv/lightdm /run/runit/service  ( artix )
#sudo systemctl enable lightdm.service  ( arch )

sudo pacman -S --noconfirm nvidia nvidia-settings opencl-nvidia \
scrcpy android-tools nvtop stress \
obs-studio audacity gimp inkscape virtualbox kdeconnect blender discord telegram-desktop \
blueman bluez-utils ntfs-3g \
qemu virt-manager bridge-utils dnsmasq openbsd-netcat ovmf swtpm
# sudo usermod -aG vboxusers $USER  # enable USB usage in Virtual-Box
# bluez-runit docker-runit openssh-runit libvirt-runit   ( artix )
# sudo ln -s /run/runit/sv/docker /run/runit/service  ( artix )
# sudo touch /run/runit/service/docker/down           ( artix )
# sudo ln -s /etc/runit/sv/sshd /run/runit/service  ( artix )
# sudo touch /run/runit/service/sshd/down           ( artix )
#bluez docker openssh qemu-arch-extra  ( arch )

git clone https://aur.archlinux.org/paru.git ~/paru
cd ~/paru && makepkg -si 
paru -S betterlockscreen xwinwrap-git ttf-comic-mono-git cava picom-ibhagwan-git \
visual-studio-code-bin google-chrome anki ttyper browsh simple-mtpfs  
#plymouth-nosystemd  ( artix ) or plymouth ly  ( arch )
#sudo systemctl enable ly.service  ( arch )

#### Setup Virt-Manager ####
# sudo ln -s /etc/runit/sv/virtlogd /run/runit/service  ( artix )
# sudo touch /run/runit/service/virtlogd/down  ( artix )
# sudo ln -s /etc/runit/sv/libvirtd /run/runit/service  ( artix )
# sudo touch /run/runit/service/libvirtd/down  ( artix )
#sudo systemctl enable --now libvirtd  ( arch )
#sudo vim /etc/libvirt/libvirtd.conf  #uncmnt line 81,104  ( arch )
# sudo usermod -aG libvirt $USER
#sudo systemctl restart libvirtd  ( arch )
# sudo virsh net-define /etc/libvirt/qemu/networks/default.xml
# sudo virsh net-autostart default

# Use dash symlink for /bin/sh  - do this carefully it can break whole system 
# readlink /bin/sh  - check system shell
# sudo pacman -S checkbashisms dash
# find /usr/bin/ -type f -perm -o=r -print0 | xargs -0r gawk '/^#!.*( |[/])sh/{printf "%s\0", FILENAME} {nextfile}' | xargs -0r checkbashisms  - check if all your /usr/bin script is compatible with dash or not
# sudo ln -sfT dash /usr/bin/sh  - change dash as system shell, only run this, after you've corrected all your script for dash
# sudo vim /usr/share/libalpm/hooks/bash-update.hook >> http://0x0.st/okdY.sh || install dashbinsh from AUR  - fix overwriting symlink after update bash  

# Change DNS server to cloudflare 
sudo cat <<EOF | sudo tee /etc/resolv.conf 
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF
 
# sudo vim /etc/hosts           ( blk sites )
# /etc/pacman.conf              ( uncheck ignorepkg and put pkgname )

# Change Teletype font 
sudo setfont /usr/share/kbd/consolefonts/ter-d16b.psf.gz
sudo su root -c "echo -e FONT='ter-d16b.psf.gz' >> /etc/vconsole.conf"

# Display Asterisks while entering pswd
# sudo su root -c "echo -e Defaults pwfeedback >> /etc/sudoers"

# Boost Linux
# /etc/default/grub >> GRUB_CMDLINE_LINUX*="rhgb quiet mitigations=off"
#sudo systemctl enable fstrim.timer  ( arch )  # not for VM's - running fstrim frequently, or even using mount -o discard, might negatively affect the lifetime of poor-quality SSD

# QT_QPA_PLATFORMTHEME="qt5ct" > /etc/environment    ( fix qt5ct )
# ControllerMode = bredr > /etc/bluetooth/main.conf  ( fix bluetooth )

# /etc/locale.conf >>  ( fix suckless utilities give XOpenIM failed error )
# LANG=en_US.UTF-8
# LC_CTYPE=en_US.UTF-8
# LC_ADDRESS=en_US.UTF-8
# LC_IDENTIFICATION=en_US.UTF-8
# LC_MEASUREMENT=en_US.UTF-8
# LC_MONETARY=en_US.UTF-8
# LC_NAME=en_US.UTF-8
# LC_NUMERIC=en_US.UTF-8
# LC_PAPER=en_US.UTF-8
# LC_TELEPHONE=en_US.UTF-8
# LC_TIME=en_US.UTF-8

# Enable tap to click for Laptop
# [ ! -f /etc/X11/xorg.conf.d/40-libinput.conf ] && printf 'Section "InputClass"
#         Identifier "libinput touchpad catchall"
#         MatchIsTouchpad "on"
#         MatchDevicePath "/dev/input/event*"
#         Driver "libinput"
# 	# Enable left mouse button by tapping
# 	Option "Tapping" "on"
# EndSection' >/etc/X11/xorg.conf.d/40-libinput.conf


