#!/bin/sh                                         

########## BSPWM ##########
sudo pacman -Syu 
sudo pacman -S --noconfirm bspwm sxhkd rofi slock dunst lxappearance maim alsa-utils dbus-python

cp -r ~/dotfiles/{.zshrc,.local,.fonts,.xinitrc,.imwheelrc,.zprofile,.icons,.themes} ~/
cp -r ~/dotfiles/.config/. ~/.config
chmod +x ~/.config/bspwm/bspwmrc ~/.config/polybar/launch.sh ~/.local/bin/* ~/.config/sxiv/exec/key-handler

git clone https://github.com/LukeSmithxyz/dmenu.git ~/Downloads/dmenu
cd ~/Donwloads/dmenu && sudo make clean install

git clone https://github.com/dracula/gtk.git ~/.themes/Dracula
sudo cp -r ~/.icons/PapirusFlatMix/cursors /usr/share/icons/Adwaita 
sudo cp -r ~/.icons/PapirusFlatMix /usr/share/icons
sudo cp -r ~/.themes/* /usr/share/themes

sudo pacman -S --noconfirm cargo ttf-jetbrains-mono ttf-font-awesome terminus-font \
     noto-fonts noto-fonts-emoji noto-fonts-cjk ttf-joypixels ttf-font-awesome  \
     linux-headers firefox \
     lsd exa bat wget curl fzf aria2 \
     neovim ripgrep nodejs npm \
     openssh mate-calc reflector \
     dialog cmake libconfig dash wmctrl imwheel \
     pipewire pulseaudio pavucontrol \
     dhcpcd networkmanager wireless_tools net-tools \
     tree ncdu thunar thunar-archive-plugin ranger rsync unrar unzip zip p7zip tar  \
     fortune-mod htop neofetch bpytop \
     speedtest-cli trash-cli yt-dlp transmission-cli \
     imagemagick sxiv xwallpaper ffmpeg python-pywal mpv \
     intel-ucode virtualbox-guest-utils python-pip xdotool \
     zsh-syntax-highlighting zsh-completions zsh-autosuggestions \
     unclutter jq xdg-user-dirs xorg xclip
     
#linux-lts linux-lts-headers 
cargo install ttyper stylua

#sudo systemctl enable vboxservice

#sudo pacman -Sy lightdm lightdm-gtk-greeter lightdm-gtk-greeter-settings
##dm-tool switch-to-greeter
#sudo systemctl enable lightdm.service

git clone --depth 1 https://github.com/wbthomason/packer.nvim \
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
 
pip3 install pynvim black flake8 sourcery
sudo pacman -S --noconfirm ueberzug eslint ccls shfmt shellcheck lazygit
sudo npm i -g prettier astyle 
sudo npm i emmet html tailwindcss live-server

#
sudo pacman -S --noconfirm nvidia nvidia-utils nvidia-settings opencl-nvidia os-prober \
scrcpy android-tools nvtop stress \
obs-studio audacity gimp inkscape kdeconnect blender discord docker \
deluge telegram-desktop \
bluez bluez-utils blueman ntfs-3g \
virt-manager qemu bridge-utils dnsmasq openbsd-netcat ovmf qemu-arch-extra

#sudo systemctl enable --now libvirtd
#sudo vim /etc/libvirt/libvirtd.conf  #uncmnt line 81,104
#sudo usermod -aG libvirt bot
#sudo systemctl restart libvirtd
#sudo virsh net-define /etc/libvirt/qemu/networks/default.xml
#sudo virsh net-autostart default

sudo systemctl enable bluetooth
sudo systemctl enable bluetooth.service
sudo systemctl enable fstrim.timer

git clone https://aur.archlinux.org/yay.git ~/yay 
cd ~/yay && makepkg -si
yay -S --noconfirm spotify-adblock notion-app google-chrome ly polybar preload kitty playerctl zathura visual-studio-code-bin packettracer

sudo systemctl enable ly.service 

mkdir ~/{Desktop,Documents,Downloads,Music,Pictures,Videos} 

sudo cat <<EOF | sudo tee /etc/resolv.conf 
nameserver 1.1.1.1
nameserver 8.8.8.8
EOF
 
setfont /usr/share/kbd/consolefonts/ter-c16b.psf.gz
sudo cat <<EOF | sudo tee /etc/vconsole.conf
FONT=ter-c16b.psf.gz
EOF


#xdg-mime query filetype (file)  #check filetype
#xdg-mime query default (file/type)  #check default app of filetype
xdg-mime default sxiv.desktop image/jpeg
xdg-mime default sxiv.desktop image/jpg
xdg-mime default sxiv.desktop image/png
xdg-mime default inkscape.desktop image/svg+xml
xdg-mime default org.pwmt.zathura.desktop application/pdf

# uncmnt zsh plugins of arch
# vim /etc/pacman.conf # uncheck ignorepkg and put pkgname
