#!/bin/bash

#### VOID ####
sudo mkdir /usr/share/grub/themes # same steps of Arch / Debian

#### ARCH ####
sudo cp -r catppuccin-mocha-grub-theme /usr/share/grub/themes/
echo 'GRUB_THEME="/usr/share/grub/themes/catppuccin-mocha-grub-theme/theme.txt"' | sudo tee -a /etc/default/grub
sudo grub-mkconfig -o /boot/grub/grub.cfg

#### DEBIAN ####
# sudo cp -r catppuccin-mocha-grub-theme /boot/grub/themes
# echo 'GRUB_THEME="/boot/grub/themes/catppuccin-mocha-grub-theme/theme.txt"' | sudo tee -a /etc/default/grub
# sudo rm -rf /usr/share/images/desktop-base/desktop-grub.png
# sudo grub-mkconfig -o /boot/grub/grub.cfg

#### Another Method For Debian ####
#sudo rm -rf /boot/grub/themes/kali/* && sudo cp -r catppuccin-mocha-grub-theme/* /boot/grub/themes/kali
#sudo grub-mkconfig -o /boot/grub/grub.cfg

#### For ALL distro ####
echo 'menuentry "Reboot" --class restart {
  reboot
}
menuentry "ShutDown" --class shutdown {
  halt
}' | sudo tee -a /etc/grub.d/40_custom

sudo grub-mkconfig -o /boot/grub/grub.cfg

#Remove Grub menu showing 'Get by holding ESC'
# GRUB_TIMEOUT_STYLE=hidden

#Grub is not detecting all systems (dual-boot)
# GRUB_DISABLE_OS_PROBER=false

#/etc/default/grub (modify 1920x1080 to your screen resolution)
# GRUB_GFXMODE=1920x1080

#Grub isn't detecting the theme
# GRUB_TERMINAL_OUTPUT="console"
