#!/bin/sh

# ctrl x them shortkey
while read file
do	
	case "$1" in
	"d") mv "$file"	~/.local/share/Trash/files ;;
	"r") convert -rotate 90 "$file" "$file" ;; 
	"c") cat "$file" | xclip -sel c -t image/png && notify-send "$file Copied ";;
	"g") gimp "$file" ;;
	"w") xwallpaper --zoom	"$file" ;;
	esac
done	
