#!/bin/sh

# ctrl x them shortkey
while read file
do	
	case "$1" in
  "w") xwallpaper --zoom "$file" & ;;
	"d") mv "$file"	~/.local/share/Trash/files ;;
	"r") convert -rotate 90 "$file" "$file" ;; 
  "R") convert -rotate 90 "$file" "$file" ;; 
  "f") convert -flop "$file" "$file" ;;
	"c") cat "$file" | xclip -sel c -t image/png && notify-send "$file Copied ";;
	"y") readlink -f "$file" | xclip -sel clip &&
       notify-send "$(readlink -f "$file") path copied to clipboard" & ;;
	"g") gimp "$file" ;;
	esac
done
