#!/bin/sh

# Replace sudo with doas
# alias sudo='doas'

# Kali
# alias install='sudo nala install'
# alias update='sudo nala update'
# alias uplist='apt list --upgradable'
# alias remove='sudo nala purge'
# alias clean='sudo apt -y autoremove; sudo apt clean'
# alias fix='sudo dpkg --configure -a; sudo apt --fix-broken install -y; sudo apt install -f; sudo apt update --fix-missing'
# alias installed='sudo apt list --installed'
# bigpkg() {
# 	dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | awk '{size=$1/1024; name=$2; printf "%.2f MB\t%s\n", size, name}'
# }

# Arch
alias install="sudo pacman -Sy"
alias update="sudo pacman -Syyu && echo '########## ⬆️AUR ##########'; paru -Sua"
alias remove="sudo pacman -Rns"
alias clean='sudo pacman -Rns $(pacman -Qtdq); sudo pacman -Sc --noconfirm; echo "########## 🚮cleaning Paru cache ##########"; rm -rf ~/.cache/paru'
alias unlock="sudo rm /var/lib/pacman/db.lck"
alias installed="grep -i installed /var/log/pacman.log"
alias bigpkg="expac -H M '%m\t%n' | sort -h | nl"

# Runit
alias doc-on="sudo sv start docker"
alias doc-off="sudo sv stop docker"
alias vm-on="sudo sv start libvirtd virtlogd spice-vdagentd"
alias vm-off="sudo sv stop libvirtd virtlogd spice-vdagentd"

# Systemd
# alias doc-on="sudo systemctl start docker.socket"
# alias doc-off="sudo systemctl stop docker.socket"
# alias vm-on="sudo systemctl start libvirtd.service"
# alias vm-off="sudo systemctl stop libvirtd.service"
alias sysctlist="systemctl list-unit-files --type=service"
alias probe="sudo -E hw-probe -all -upload"
alias sysctlfail="systemctl --failed"
alias jctl="sudo journalctl -p 3 -xb"
alias cleanjctl="sudo journalctl --vacuum-time=2weeks"
alias chain="sudo systemd-analyze critical-chain"
alias blame="sudo systemd-analyze blame"

alias la="exa --icons"
alias ls="ls --color=auto"
alias lt="exa --icons --tree"
alias ll="exa --icons -lgha --group-directories-first"
alias lm="ls -t -1"
alias lsn="exa | wc -l"
alias l-="ls -l | grep -v 'd'"
alias ld="ls -l | grep '^d'"
alias l.="ls -A | grep '^\.'"

alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip --color=auto"

alias ..="cd .."
alias ...="cd ../.."
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias del="gio trash"
alias tre="trash-restore"
alias less="less -R"
alias mkdir="mkdir -pv"
alias trim="sudo fstrim -va"
alias logout='sudo pkill -u "$USER"'
alias sdn="sudo shutdown -h now"

alias lg="lazygit"
alias add.="git add ."
alias addup="git add -u"
alias branch="git branch"
alias checkout="git checkout"
alias clone="git clone"
alias commit="git commit -m"
alias fetch="git fetch"
alias status="git status"
alias tag="git tag"
alias newtag="git tag -a"
alias pull="git pull origin"
alias push="git push origin"

alias rr="curl https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"
alias speedtest="curl -s https://raw.githubusercontent.com/sivel/speedtest-cli/master/speedtest.py | python -"
alias tb="nc termbin.com 9999"
alias myip="curl ifconfig.me; echo"
alias php-server="php -S 0.0.0.0:8000"
alias py-server="python -m http.server 8000"
alias logs="sudo find /var/log -type f -exec file {} \; | grep 'text' | cut -d' ' -f1 | sed -e's/:$//g' | grep -v '[0-9]$' | xargs tail -f"
alias multitail="multitail --no-repeat -c"

alias ff='fd --type f --hidden --exclude .git | fzf --preview "bat --color=always --style=numbers --line-range=:500 {}" | xargs -r "$EDITOR"'
alias bigf="du -hxs * | sort -rh | head"
alias psmem="ps axch -o cmd,%mem --sort=-%mem | head"
alias pscpu="ps axch -o cmd,%cpu --sort=-%cpu | head"
alias microcode="grep . /sys/devices/system/cpu/vulnerabilities/*"
alias userlist="cut -d: -f1 /etc/passwd | sort"

alias ping="ping -c 6"
alias ports="netstat -tulanp"
alias copy="rsync --progress -aluvr"

alias df="df -h"
alias du="du -h"
alias free="free -h"
alias bc="bc -ql"
alias hw="hwinfo --short"
alias dmesg="sudo dmesg -T"
alias shred="shred -uvzn3"
alias bat="bat --theme OneHalfDark"
alias cat="bat --theme OneHalfDark -p"
alias pu="pushd"
alias po="popd"
alias ffmpeg="ffmpeg -hide_banner"
alias ffplay="ffplay -hide_banner"
alias ffprobe="ffprobe -hide_banner"
alias tsm="transmission-remote"
# alias wget="wget --hsts-file=/dev/null"
alias wget='wget --hsts-file="$HOME/.cache/wget-hsts"'
alias yarn='yarn --use-yarnrc "$XDG_CONFIG_HOME/yarn/config"'
alias nvidia-setting='nvidia-settings --config="$XDG_CONFIG_HOME"/nvidia/settings'

alias iv="sxiv"
alias za="zathura"
alias vim="nvim"
alias se="sudoedit"
alias mpc="mpd 2>/dev/null; ncmpcpp"
alias aft="android-file-transfer"
alias ytdl-vid="yt-dlp -f bestvideo+bestaudio"
alias ytdl-aud="yt-dlp --extract-audio --audio-format m4a"

# for Arch Linux only
# alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
# alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
# alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
# alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"
