#!/bin/sh

if [ -f /etc/arch-release ]; then
  alias big-pkg="expac -H M '%m\t%n' | sort -h | nl"
	alias clean='sudo pacman -Rns $(pacman -Qtdq); sudo paccache -r; paru -Sc --noconfirm; rm -rf ~/.cache/paru'
	alias installed="grep -i installed /var/log/pacman.log"
elif [ -f /etc/debian_version ]; then
	alias fix-pkg="sudo dpkg --configure -a; sudo apt --fix-broken install -y; sudo apt install -f; sudo apt update --fix-missing"
	alias clean="sudo apt -y autoremove; sudo apt clean"
	alias installed="sudo apt list --installed"
else
	:
fi

if grep -q '^runit$' </proc/1/comm; then
	alias doc-on="sudo sv start docker"
	alias doc-off="sudo sv stop docker"
	alias vm-on="sudo sv start libvirtd virtlogd"
	alias vm-off="sudo sv stop libvirtd virtlogd"
elif grep -q '^systemd$' </proc/1/comm; then
	alias doc-on="sudo systemctl start docker"
	alias doc-off="sudo systemctl stop docker"
	alias vm-on="sudo systemctl start libvirtd libvirtd{,-ro,-admin,-tcp,-tls}.socket"
	alias vm-off="sudo systemctl stop libvirtd libvirtd{,-ro,-admin,-tcp,-tls}.socket"
	alias jc="sudo journalctl -p 3 -xb"
  alias jc-clean="sudo journalctl --vacuum-time=2weeks"
  alias sc-blame="sudo systemd-analyze blame"
  alias sc-chain="sudo systemd-analyze critical-chain"
	alias sc-fail="systemctl --failed"
	alias sc-list="systemctl list-unit-files --type=service"
else
	:
fi

alias ls="ls --color=auto"
alias ll="eza -alh 2>/dev/null || ls -alh"
alias lm="ls -t -1"
alias l-="ls -l | grep -v 'd'"
alias ld="ls -ld */"
alias lh="ls -ld .*"

alias grep="grep --color=auto"
alias diff="diff --color=auto"
alias ip="ip --color=auto"

alias ..="cd .."
alias ...="cd ../.."
alias rm="rm -iv"
alias cp="cp -iv"
alias mv="mv -iv"
alias mkdir="mkdir -pv"
alias clr="clear"
alias fix-faillock='faillock --user "$USER" --reset'

alias rr="curl https://raw.githubusercontent.com/keroserene/rickrollrc/master/roll.sh | bash"
alias matrix='tr -c "[:xdigit:]" " " </dev/urandom'
alias tb="nc termbin.com 9999"
alias ff='fd -t f | fzf --preview "cat {}" | xargs -r "$EDITOR"'
alias vuln="grep . /sys/devices/system/cpu/vulnerabilities/*"
alias dmesg="sudo dmesg -T"
alias hw="hwinfo --short"
alias ports="sudo ss -tulnp"
alias bf="dust -ir 2>/dev/null || du -sh * | sort -rh"
alias df="df -h"
alias bc="bc -ql"
alias iv="xrdb merge ~/.config/x11/xresources; nsxiv"
alias pywal="wal -qi ~/.local/share/walls >/dev/null"
alias ytdlv="yt-dlp --external-downloader aria2c"
alias ytdla="yt-dlp -x --audio-format mp3 --audio-quality 0"
