#!/bin/sh
# shellcheck disable=SC2155

# Paths
export PATH="$PATH:$(du "$HOME/.local/bin" | cut -f2 | paste -sd ':')"
export PATH="$PATH:$HOME/.local/share/cargo/bin"

# Default programs
export MANPAGER="nvim +Man!"
export EDITOR="nvim"
export TERMINAL="kitty"
export READER="zathura"
export BROWSER="google-chrome-stable"

# XDG paths
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_DATA_HOME="$HOME/.local/share"
export XDG_CACHE_HOME="$HOME/.cache"

# Fixing paths
export GOPATH="$XDG_DATA_HOME/go"
export GOMODCACHE="$XDG_CACHE_HOME/go/mod"
export CARGO_HOME="$XDG_DATA_HOME/cargo"
export RUSTUP_HOME="$XDG_DATA_HOME/rustup"
export SOLARGRAPH_CACHE="$XDG_CACHE_HOME/solargraph"
export OMNISHARPHOME="$XDG_CONFIG_HOME/omnisharp"
export SQLITE_HISTORY="$XDG_DATA_HOME/sqlite_history"
export PYTHONPYCACHEPREFIX="$XDG_CACHE_HOME/python"
export PYTHONSTARTUP="$XDG_CONFIG_HOME/python/pythonrc"
export JULIA_DEPOT_PATH="$XDG_DATA_HOME/julia:$JULIA_DEPOT_PATH"
export JULIAUP_DEPOT_PATH="$XDG_DATA_HOME/julia"
export GRADLE_USER_HOME="$XDG_DATA_HOME/gradle"
export SDKMAN_DIR="$XDG_DATA_HOME/sdkman"
export KODI_DATA="$XDG_DATA_HOME/kodi"
export CUDA_CACHE_PATH="$XDG_CACHE_HOME/nv"
export GTK2_RC_FILES="$XDG_CONFIG_HOME/gtk-2.0/gtkrc-2.0"
export PASSWORD_STORE_DIR="$XDG_DATA_HOME/password-store"
export GNUPGHOME="$XDG_DATA_HOME/gnupg"
export WGETRC="$XDG_CONFIG_HOME/wget/wgetrc"
export ANSIBLE_CONFIG="$XDG_CONFIG_HOME/ansible/ansible.cfg"
## $ npm config edit
export NPM_CONFIG_USERCONFIG="$XDG_CONFIG_HOME/npm/npmrc"
export NODE_REPL_HISTORY="$XDG_DATA_HOME/node_repl_history"
## $ mkdir -p "$XDG_DATA_HOME"/wineprefixes
export WINEPREFIX="$XDG_DATA_HOME/wineprefixes/default"

export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
export HISTFILE="$XDG_DATA_HOME/history"
export XINITRC="$XDG_CONFIG_HOME/x11/xinitrc"
export INPUTRC="$XDG_CONFIG_HOME/shell/inputrc"
export ICEAUTHORITY="$XDG_CACHE_HOME/ICEauthority"

export LESSHISTFILE="-"            # disable files
export QT_QPA_PLATFORMTHEME="gtk2" # have QT use gtk2 theme
export QT_QPA_PLATFORMTHEME="qt5ct"
export _JAVA_AWT_WM_NONREPARENTING=1 # fix Java applications
export AWT_TOOLKIT="MToolkit wmname LG3D"
