#!/bin/sh

ext() {
	if [ -f "$1" ]; then
		case $1 in
		*.tar.bz2 | *.tbz2) tar xjf "$1" ;;
		*.tar.gz | *.tgz) tar xzf "$1" ;;
		*.tar | *.tar.xz) tar xf "$1" ;;
		*.tar.zst) unzstd "$1" ;;
		*.bz2) bunzip2 "$1" ;;
		*.gz) gunzip "$1" ;;
		*.zip) unzip "$1" ;;
		*.rar) unrar x "$1" ;;
		*.Z) uncompress "$1" ;;
		*.7z) 7z x "$1" ;;
		*.deb) ar x "$1" ;;
		*) echo "'$1' cannot be extracted via ext()" ;;
		esac
	else
		echo "'$1' is not a valid file"
	fi
}

joke() {
	curl -sSL https://v2.jokeapi.dev/joke/Any | jq -r '.category, .setup, .delivery'
}

qot() {
	curl https://api.quotable.io/random -s | jq -r '"\(.content) - \(.author)"'
}

cht() {
	sh -c "curl cheat.sh/$1"
}

wttr() {
	sh -c "curl wttr.in/$1"
}

rate() {
	sh -c "curl rate.sx/$1"
}

lazyg() {
	git add .
	git commit -m "$1"
	git push
}

lfcd() {
	dir=$(lf -print-last-dir "$@")
	while ! cd "$dir" 2>/dev/null; do
		dir=$(dirname "$dir")
	done
}

# For some reason, rot13 pops up everywhere
rot13() {
	if [ $# -eq 0 ]; then
		tr 'a-mn-zA-MN-Z' 'n-za-mN-ZA-M'
	else
		echo "$*" | tr 'a-mn-zA-MN-Z' 'n-za-mN-ZA-M'
	fi
}

# Stop watch
sw() {
	elapsed_time=0
	while true; do
		clear
		printf "%02d:%02d:%02d\n" $(("$elapsed_time" / 3600)) $(("$elapsed_time" % 3600 / 60)) $(("$elapsed_time" % 60))
		elapsed_time=$((elapsed_time + 1))
		sleep 1
	done
}

bigpkgs() { [ -f /etc/debian_version ] && dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | awk '{printf "%.2f MB\t%s\n", $1/1024, $2}' || echo "Not running Debian"; }
