#!/bin/sh

if [ -f "$XDG_CONFIG_HOME/.config/x11/xprofile" ]; then
	. "$XDG_CONFIG_HOME/.config/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

fav=bspwm
case "$1" in
bspwm) bspwm ;;
gnome) gnome-session ;;
*) exec dbus-launch --sh-syntax --exit-with-session $fav ;;
esac
