#!/bin/sh

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xprofile"
else
	. "$HOME/.xprofile"
fi

if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc" ]; then
	. "${XDG_CONFIG_HOME:-$HOME/.config}/x11/xinitrc"
else
	. "$HOME/.xinitrc"
fi


fav=bspwm

case "$1" in
	bspwm) bspwm ;;
	xfce) startxfce4 ;;
	dwm) ssh-agent dwm ;;
	*) exec $fav ;;
esac


#/usr/share/xsession    -- session path
