#!/bin/sh

if [ "$(readlink -f /sbin/init)" != "/usr/lib/systemd/systemd" ]; then
	killall pipewire pipewire-pulse wireplumber
	/usr/bin/pipewire &
	/usr/bin/pipewire-pulse &
	/usr/bin/wireplumber &
fi
