#!/bin/sh

# kill if already running
killall -9 pipewire pipewire-pulse wireplumber kdeconnect-indicator

pipewire &
pipewire-pulse &
wireplumber &
kdeconnect-indicator &
xrdb merge ~/.config/x11/xresources
