#!/usr/bin/env sh

HYPRGAMEMODE=$(hyprctl getoption animations:enabled | awk 'NR==2{print $2}')
if [ "$HYPRGAMEMODE" = 1 ]; then
	hyprctl --batch "\
        keyword animations:enabled 0;\
        keyword decoration:blur 0;\
        keyword general:border_size 1;\
        keyword decoration:rounding 0"
	notify-send -t 600 "Decor "
	exit
fi
hyprctl reload && notify-send -t 400 "Restart hypr "
