#!/bin/bash

# Function to adjust the gaps by the given value
adjust_gaps() {
	current_gaps=$(cat "$CACHE_DIR/gaps.txt")
	new_gaps=$((current_gaps + $1))
	echo "$new_gaps" >"$CACHE_DIR/gaps.txt"

	hyprctl --batch "keyword general:gaps_in $new_gaps; \
                  keyword general:gaps_out $new_gaps; \
                  keyword general:gaps_in $new_gaps; \
                  keyword general:gaps_out $new_gaps"
}

# Check if an argument is provided to the script
if [ $# -ne 1 ]; then
	echo "Usage: $0 <increase|decrease>"
	exit 1
fi

# Set the cache directory
CACHE_DIR="$HOME/.cache"

# Create the gaps.txt file if it doesn't exist and initialize it with 0
if [ ! -e "$CACHE_DIR/gaps.txt" ]; then
	echo "0" >"$CACHE_DIR/gaps.txt"
fi

# Determine whether to increase or decrease based on the argument
case "$1" in
"increase")
	adjust_gaps 4
	;;
"decrease")
	adjust_gaps -4
	;;
*)
	exit 1
	;;
esac
