#!/bin/sh

workspace="${1:-magic}"
cmd="${2:-kitty}"

if hyprctl clients | grep -q "special:$workspace"; then
	hyprctl dispatch togglespecialworkspace "$workspace"
else
	hyprctl dispatch "exec [workspace special:$workspace] $cmd"
fi
