#!/bin/sh

dir="${HOME}/.local/share/walls"
BG="$(find "$dir" -name '*.jpg' -o -name '*.png' | shuf -n1)"

# Name of the program to check
PROGRAM="swww-daemon"
trans_type="simple"

# Check if the program is running
if pgrep "$PROGRAM" >/dev/null; then
	swww img "$BG" --transition-fps 255 --transition-type $trans_type --transition-duration 1
else
	swww init && swww img "$BG" --transition-fps 255 --transition-type $trans_type --transition-duration 1
fi
