#!/bin/sh

if [ -d "$HOME/.local/share/walls" ]; then
	set -- "$HOME/.local/share/walls"/*
	if [ -e "$1" ]; then
		sudo cp "$1" "/etc/lightdm/lightdm-wall.jpg" >/dev/null 2>&1
	fi
fi

echo '[greeter]
background = /etc/lightdm/cyberpunk-girl.jpg
font-name = MapleMono NF 12
hide-user-image = true
theme-name = Sweet-Dark-v40
icon-theme-name = elementary
clock-format = %a, %d %b 🕗 %I:%M
indicators = ~host;~spacer;~clock;~spacer;~session;~power' | sudo tee -a /etc/lightdm/lightdm-gtk-greeter.conf
