#!/bin/sh

# sudo pacman -S --noconfirm lightdm-gtk-greeter-settings
# dm-tool switch-to-greeter

if [ -d "$HOME/.local/share/walls" ]; then
	sudo cp ~/.local/share/walls/astro.jpg /etc/lightdm/wallpaper.jpg 2>/dev/null
fi

echo '[greeter]
background = /etc/lightdm/wallpaper.jpg
font-name = Cantarell 12
hide-user-image = true
theme-name = Sweet-Dark
icon-theme-name = Adwaita 
clock-format = %a, %d %b 🕗 %I:%M
indicators = ~host;~spacer;~clock;~spacer;~session;~power' | sudo tee -a /etc/lightdm/lightdm-gtk-greeter.conf
