#!/bin/sh

session_type="$XDG_SESSION_TYPE"
copy_command="xclip -sel clip"
wallpaper_command="xwallpaper --zoom"
[ "$session_type" = "wayland" ] && {
	copy_command="wl-copy"
	wallpaper_command="swww img"
}

# ctrl x then key
while read -r file; do
	case "$1" in
	"w") $wallpaper_command "$file" & ;;
	"d") gio trash "$file" || mv "$file" ~/.local/share/Trash/files ;;
	"r") convert -rotate 90 "$file" "$file" ;;
	"R") convert -rotate -90 "$file" "$file" ;;
	"f") convert -flop "$file" "$file" ;;
	"c") $copy_command -t image/png <"$file" && notify-send "$file Copied" ;;
	"y") readlink -f "$file" | $copy_command &&
		notify-send "$(readlink -f "$file") path copied to clipboard" & ;;
	"g") gimp "$file" ;;
	esac
done
