#!/bin/sh

copy="xclip -sel clip"
wall="xwallpaper --zoom"
if [ -n "$WAYLAND_DISPLAY" ]; then
  copy="wl-copy"
  wall="swww img"
fi

# ctrl x then key
while read -r file; do
  case "$1" in
  "w") $wall "$file" & ;;
  "d") gio trash "$file" || mv "$file" ~/.local/share/Trash/files ;;
  "r") magick "$file" -rotate 90 "$file" ;;
  "R") magick "$file" -rotate -90 "$file" ;;
  "f") magick "$file" -flop "$file" ;;
  "c") $copy -t image/png <"$file" && notify-send "$file copied" ;;
  "y") readlink -f "$file" | $copy && notify-send "$(readlink -f "$file") path copied to clipboard" ;;
  "g") setsid -f gimp "$file" ;;
  esac
done
