format = """
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$character"""

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "
style = "bright-black"

[git_state]
format = '[\($state( $progress_current/$progress_total)\)]($style) '
style = "bright-black"

[git_status]
ahead = ""
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_metrics]
disabled = false

[directory]
style = "blue"
read_only = " "
truncation_length = 4
truncate_to_repo = false

[character]
success_symbol = "[❯](pink)"
error_symbol = "[❯](red)"
vicmd_symbol = "[❮](green)"
