#!/bin/sh

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

# bspc config border_width 1
bspc config window_gap 4
# bspc config top_padding 29
bspc config pointer_motion_interval 16

bspc config split_ratio 0.48
bspc config borderless_monocle true
# bspc config gapless_monocle false
bspc config focus_follows_pointer true

bspc config focused_border_color "#F8F8F2"
bspc config normal_border_color "#040404"
bspc config presel_feedback_color "#313244"

bspc rule -a Screenkey manage=off
bspc rule -a Spotify desktop='^9'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a pavucontrol state=floating center=on
bspc rule -a Lxappearance state=floating center=on
bspc rule -a scratchpad locked=on sticky=on state=floating

# Autostart
xsetroot -cursor_name left_ptr &
pidof -q sxhkd || sxhkd -c ~/.config/bspwm/sxhkdrc &
sh ~/.config/polybar/launch.sh &
xwallpaper --zoom ~/.local/share/walls/wallpaper.jpg &
xset r rate 300 50 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# xcape -e 'Super_L=Control_L|Escape' &
