#!/bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 1
bspc config window_gap 4
bspc config top_padding 29
bspc config pointer_motion_interval 16

bspc config split_ratio 0.48
bspc config borderless_monocle true
bspc config gapless_monocle false
bspc config focus_follows_pointer true

bspc config focused_border_color "#f8f8f2"
bspc config normal_border_color "#040303"
bspc config presel_feedback_color "#44475a"

bspc rule -a Screenkey manage=off
bspc rule -a Gimp state=floating
bspc rule -a Spotify desktop='^9'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a Pavucontrol state=floating center=on
bspc rule -a Lxappearance state=floating center=on
bspc rule -a scratchpad locked=on sticky=on state=floating rectangle=999x800+460+90

# Autostart
xsetroot -cursor_name left_ptr &
sh ~/.config/sxhkd/sxhkd.sh &
sh ~/.config/polybar/launch.sh &
xwallpaper --zoom ~/.local/share/walls/wallpaper.jpg &
xset r rate 280 60 &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1
# xcape -e 'Super_L=Control_L|Escape' &
