#!/bin/sh

bspc monitor -d 0 1 2 3 4 5 6 7 8 9

bspc config border_width 1
bspc config window_gap 12
bspc config pointer_motion_interval 16
bspc config split_ratio 0.5
bspc config borderless_monocle true
bspc config focus_follows_pointer true
bspc config focused_border_color "#F8F8F2"
bspc config presel_feedback_color "#44475A"

bspc rule -a Screenkey manage=off
bspc rule -a pavucontrol state=floating center=on

# Autostart
pkill sxhkd 2>/dev/null; sxhkd -c ~/.config/bspwm/sxhkdrc &
pkill xcape 2>/dev/null; xcape -e "Super_L=Alt_L|F1" &
xsetroot -cursor_name left_ptr &
~/.config/polybar/launch.sh &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
xwallpaper --zoom ~/.local/share/walls/wallpaper.jpg &
