#!/bin/sh

# - Dependency
# curl https://raw.githubusercontent.com/phenax/bsp-layout/master/install.sh | bash -;

if ! pgrep -x "bspwm" >/dev/null; then
	exit 1
fi

current_layout=$(bsp-layout get)

case "$current_layout" in
"tiled")
	bsp-layout set tall
	notify-send -t 600 ""
	;;
*)
	bsp-layout set tiled
	notify-send -t 600 ""
	;;
esac
