#!/bin/bash


[colors]
background = #000
background-alt = #444
foreground = #70F79F
foreground-alt = #636360
primary = #ffb52a
secondary = #e60053
alert = #bd2c40


[bar/example]
width = 100%
height = 26
offset-y = 0.3%
offset-x = 0.3%
fixed-center = true
monitor = "HDMI-0"

background = ${colors.background}
foreground = ${colors.foreground}

line-size = 3
padding-left = 0
padding-right = 2
module-margin-left = 0
module-margin-right = 1

font-0 = JetBrainsMono Nerd Font:style=Bold:pixelsize=11;3
font-1 = Material Design Icons:style=Regular:size=13;3
font-2 = NotoColorEmoji:fontformat=truetype:scale=10:antialias=false;
font-3 = unifont:fontformat=truetype:size=8:antialias=false;0

wm-restack = bspwm
modules-left = bspwm xwindow uptime spotify
modules-center = date 
modules-right = nettraf pulseaudio cpu memory temperature filesystem

tray-position = right 
cursor-click = pointer
cursor-scroll = ns-resize
screenchange-reload = true


 
################  MODULES ################


[module/nettraf]  
type = custom/script  
exec = "~/.config/polybar/scripts/nettraf"  
interval = 1
format-foreground = #B175EC


[module/spotify]
type = custom/script  
exec = "~/.config/polybar/scripts/spotify"  
tail = true
format-foreground = #FFFF66


[module/xwindow]
type = internal/xwindow
label = %title:0:27:...%
format-foreground = #FF61BE


[module/bspwm]
type = internal/bspwm
label-focused = %index%
label-focused-background = ${colors.background-alt}
label-focused-underline= ${colors.primary}
label-focused-padding = 2
label-occupied = %index%
label-occupied-padding = 2
label-urgent = %index%!
label-urgent-background = ${colors.alert}
label-urgent-padding = 2
label-empty = %index%
label-empty-foreground = ${colors.foreground-alt}
label-empty-padding = 1


[module/date]
type = internal/date
interval = 1
date = 󰃭 %a %d %b,
time = 󰥔 %I:%M:%S %p
format-foreground = #acd7ff
label = %date% %time% 


[module/cpu]
type = internal/cpu
interval = 2
format = <label> 
format-padding = 0
format-margin = 1
label = 󰍛%percentage%
format-foreground = #3CB9FC


[module/filesystem]
type = internal/fs
interval = 30
mount-0 = /
label-mounted = "  %free%"
label-mounted-foreground = #06FF00
label-unmounted = %mountpoint% 


[module/memory]
type = internal/memory
interval = 2
format-foreground = #ffb86c
label = 󰘚%mb_used%


[module/uptime]
type = custom/script
exec = uptime --pretty | sed 's/up //' | sed 's/\ years\?,/y/' | sed 's/\ weeks\?,/w/' | sed 's/\ days\?,/d/' | sed 's/\ hours\?,\?/h/' | sed 's/\ minutes\?/m/'
interval = 60
format-prefix = " "
format-foreground = #06FF00


[module/pulseaudio]
type = internal/pulseaudio
format-volume = <ramp-volume> <label-volume>
label-volume-foreground = #FFFF66
use-ui-max = false
label-muted = "  0"
label-muted-foreground = #666
label-volume = %percentage%
ramp-volume-0 = " "
ramp-volume-1 = " "
ramp-volume-2 = " "
click-right = pavucontrol &


#[module/powermenu]
#type = custom/menu
expand-right = true
format-spacing = 2
label-open = " %{A}"
label-close = 
menu-0-0 = ""
menu-0-0-exec = reboot
menu-0-1 = ""
menu-0-1-exec = poweroff
format-foreground = #DD0004


[module/temperature]
type = internal/temperature
thermal-zone = 0
hwmon-path = /sys/devices/platform/coretemp.0/hwmon/hwmon1/temp1_input
warn-temperature = 70
format = <ramp> <label>
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-warn = <label-warn>
label = %temperature-c%
label-warn = "  %temperature-c%"
label-warn-foreground = #f00
ramp-0 = " "
ramp-foreground = #fc4949

