#!/bin/sh

#sudo apt install -y nodejs npm ueberzug eslint ccls shfmt shellcheck lua-check
#sudo pacman -S --noconfirm nodejs npm ueberzug eslint ccls shfmt shellcheck luacheck lazygit
pip install pynvim black flake8 sourcery
cargo install stylua
sudo npm i -g prettier astyle truecallerjs emmet html tailwindcss live-server

