#!/bin/sh

# Build Neovim
#sudo apt install -y ninja-build gettext libtool libtool-bin cmake pkg-config doxygen
#git clone https://github.com/neovim/neovim.git ~/.config/neovim && cd ~/.config/neovim
#make -j4 && sudo make install

# Packer install
git clone --depth 1 https://github.com/wbthomason/packer.nvim \
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim
 
#sudo apt install -y nodejs npm ccls shfmt shellcheck ueberzug 
#cargo install stylua

#sudo pacman -S --noconfirm nodejs npm ccls shfmt shellcheck ueberzug stylua lazygit 
sudo npm i -g prettier astyle luacheck emmet eslint html tailwindcss live-server
pip install pynvim black flake8 sourcery 

