require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorizer"
require "user.comment"
require "user.alpha"
require "user.autopairs"
require "user.colorscheme"
require "user.lualine"
require "user.impatient"
require "user.illuminate"
require "user.rainbow-bracket"
require "user.treesitter"

require "user.telescope"
require "user.autocommands"
require "user.indentline"
require "user.nvim-tree"
require "user.toggleterm"
require "user.bufferline"

require "user.cmp"
require "user.whichkey"
require "user.lsp"
-- require "user.dap"
