#!/bin/sh


select=$(bluetoothctl devices | awk {'print $3'})
MAC=$(bluetoothctl devices | grep $select | awk {'print $2'})

connect=$(bluetoothctl info $MAC | grep Connected: | awk '{print $2}')
if [[ $connect = no ]]; then 
	notify-send "Connecting to $select"
	bluetoothctl connect $MAC || notify-send "Failed to Connect"
else
	notify-send "Disconnecting from $select"
	bluetoothctl disconnect $MAC 
fi
