#!/bin/sh

bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -p "Select Wifi  " -l 20 | cut -d' ' -f1)
pass=$(echo "" | dmenu -p "Enter Pswd  ")
nmcli device wifi connect $bssid password $pass





#!/bin/sh


ethstatus=$(nmcli d | grep eth0 | cut -d ' ' -f7)
wifistatus=$(nmcli d | grep wlan0 | cut -d ' ' -f10)


bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -p "Select Wifi  " -l 20 | cut -d' ' -f1)
pass=$(echo "" | dmenu -p "Enter Pswd  ")
nmcli device wifi connect $bssid password $pass


case $wifistatus in
             "connected")
              nmcli con down eth0 "Wired connection 1";;
               "disconnected")
              nmcli con up eth0 "Wired connection 1";;
esac
