#!/bin/sh

# https://github.com/adi1090x/plymouth-themes

## DEB ##
sudo cp -r lone /usr/share/plymouth/themes/
sudo plymouth-set-default-theme -R lone

## ARCH ##
# /etc/mkinitcpio.conf  `HOOKS add - plymouth after udev`
sudo mkinitcpio -p linux-lts / linux

# /etc/default/grub  `GRUB_CMDLINE_LINUX_DEFATULT add - splash rd.udev.log_priority=3 vt.global_cursor_default=0`
sudo grub-mkconfig -o /boot/grub/grub.cfg

sudo cp -r lone /usr/share/plymouth/themes/
# sudo plymouth-set-default-theme -l
sudo plymouth-set-default-theme -R lone

# sudo vim /etc/plymouth/plymouthd.conf  `ShowDelay=0 and DeviceTimeout=5`
# sudo mkinitcpio -p linux-lts / linux  `Regenerate config file for theme`
